export const commentActionTypes = {
    CREATE_COMMENT: 'CREATE_COMMENT',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    FETCH_ALL_COMMENTS: 'FETCH_ALL_COMMENTS',
    FETCH_COMMENT: 'FETCH_COMMENT',
    COMMENTS_REQUESTED: 'COMMENTS_REQUESTED'
};