export const programActionTypes = {
    CREATE_PROGRAM: 'CREATE_PROGRAM',
    UPDATE_PROGRAM: 'UPDATE_PROGRAM',
    DELETE_PROGRAM: 'DELETE_PROGRAM',
    FETCH_ALL_PROGRAMS: 'FETCH_ALL_PROGRAMS',
    FETCH_PROGRAM: 'FETCH_PROGRAM',
    PROGRAMS_REQUESTED: 'PROGRAMS_REQUESTED'
};
