export const selectedProgramsActionTypes = {
    FETCH_ALL_SELECTED_PROGRAMS: 'FETCH_ALL_SELECTED_PROGRAMS',
    ADD_TO_SELECTED: 'ADD_TO_SELECTED',
    DELETE_SELECTED_PROGRAM: 'DELETE_SELECTED_PROGRAM',
    SELECTED_PROGRAMS_REQUESTED: 'SELECTED_PROGRAMS_REQUESTED'
};
