export const selectedProgramsActionTypes = {
    FETCH_ALL_SELECTED_PROGRAMS: 'FETCH_ALL_SELECTED_PROGRAMS',
    CREATE_SELECTED_PROGRAM: 'CREATE_SELECTED_PROGRAM',
    DELETE_SELECTED_PROGRAM: 'DELETE_SELECTED_PROGRAM',
    SELECTED_PROGRAMS_REQUESTED: 'SELECTED_PROGRAMS_REQUESTED'
};
