export const userActionTypes = {
    USERS_LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    USERS_LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    USERS_REGISTRATION_REQUEST: 'USERS_REGISTRATION_REQUEST',
    USERS_REGISTRATION_SUCCESS: 'USERS_REGISTRATION_SUCCESS',
    USERS_REGISTRATION_FAILURE: 'USERS_REGISTRATION_FAILURE',
    
    USERS_UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',

    USERS_GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    USERS_GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    USERS_GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    USERS_GETBYID_REQUEST: 'USERS_GETBYID_REQUEST',
    USERS_GETBYID_SUCCESS: 'USERS_GETBYID_SUCCESS',
    USERS_GETBYID_FAILURE: 'USERS_GETBYID_FAILURE',

    USERS_LOGOUT: 'USERS_LOGOUT'
};