export const userActionTypes = {
    USERS_LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    USERS_LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    USERS_REGISTRATION: 'USERS_REGISTRATION',

    USERS_LOGOUT: 'USERS_LOGOUT',

    USERS_GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    USERS_GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    USERS_GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    USERS_GETBYID_REQUEST: 'USERS_GETBYID_REQUEST',
    USERS_GETBYID_SUCCESS: 'USERS_GETBYID_SUCCESS',
    USERS_GETBYID_FAILURE: 'USERS_GETBYID_FAILURE',
};